/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package isi.deso.tpdeso2024.utils;

/**
 *
 * @author gabic
 */


import isi.deso.tpdeso2024.utils.paneles.*;
import javax.swing.*;
import java.awt.*;

import java.awt.CardLayout;

public class InterfazGeneral extends javax.swing.JFrame {

    /*private final InterfazVendedor interfazVendedor;
    private final InterfazCliente interfazCliente;
    private final InterfazItemMenu interfazItemMenu;
    private final InterfazPedido interfazPedido;
    private InformacionInterfaz interfazActual;*/
    
    private final PanelInformacion panelItemMenu;
    private final PanelInformacion panelVendedor;
    private final PanelInformacion panelCliente;
    private final PanelInformacion panelPedido;
    
    private JButton boton_menu_seleccionado;
    
    private JDialog modal_actual;
    private JPanel panel_actual;
    //private final VendedorController vendedorController;
    private CardLayout cardLayout;
    private ButtonGroup tipo_pago_group;
    
    
    
    /**
     * Creates new form VendedorInterface
     */
    public InterfazGeneral() {
        initComponents();
        //vendedorController = VendedorController.getInstance();
        panelItemMenu = new PanelItemMenu();
        panelVendedor = new PanelVendedor();
        panelCliente = new PanelCliente();
        panelPedido = new PanelPedido();
        
        boton_menu_seleccionado = botonListaVendedores;
        
        /*interfazVendedor = new InterfazVendedor(modal_vendedor, modal_eliminar,
                                                tabla, text_field_nombre_v, text_field_direccion_v, text_field_latitud_v, text_field_longitud_v,
                                                    label_titulo_modal_vendedor, boton_confirmar_vendedor, titulo_modal_eliminar, boton_confirmar_eliminar,
                                                        boton_crear, panel_info_titulo, label_buscar);
        
        interfazCliente = new InterfazCliente(modal_cliente, modal_eliminar,
                                                tabla, text_field_cuit_c, text_field_email_c, text_field_direccion_c, text_field_latitud_c, text_field_longitud_c,
                                                    label_titulo_modal_cliente, boton_confirmar_cliente, titulo_modal_eliminar, boton_confirmar_eliminar,
                                                        boton_crear, panel_info_titulo, label_buscar);
        
        interfazItemMenu = new InterfazItemMenu(modal_item_menu, modal_eliminar,
                                                tabla, text_field_nombre_i, text_area_descripcion_i, text_field_vendedor_i, text_field_precio_i,  text_field_categoria_i,
                                                    label_titulo_modal_item_menu, boton_confirmar_item_menu, titulo_modal_eliminar, boton_confirmar_eliminar,
                                                        boton_crear, panel_info_titulo, label_buscar);
        
        interfazPedido = new InterfazPedido(modal_pedido, modal_eliminar,
                                                tabla, text_field_cliente_p,  rbutton_mp_p, rbutton_transferencia_p,
                                                    label_titulo_modal_pedido, boton_confirmar_pedido, titulo_modal_eliminar, boton_confirmar_eliminar,
                                                        boton_crear, panel_info_titulo, label_buscar);*/
        
        /*inicializarTabla(tabla);*/
        
        /*cambiarPanel(interfazVendedor, modal_vendedor);*/
        
        cambiarPanel(panelVendedor, botonListaVendedores);
    }
    
    
    public void inicializarTabla(JTable tabla){
        tabla.setRowSelectionAllowed(true);
        tabla.setColumnSelectionAllowed(false);  
        tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
        tabla.setSelectionBackground(Color.LIGHT_GRAY);
        tabla.setSelectionForeground(Color.BLUE); 
    }

    /**
     * Creates new form NewJFrame
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panel_botones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonListaVendedores = new javax.swing.JButton();
        botonListaClientes = new javax.swing.JButton();
        botonListaItemsMenu = new javax.swing.JButton();
        botonListaPedidos = new javax.swing.JButton();
        label_buscar1 = new javax.swing.JLabel();
        panel_informacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión App Delivery");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setLastDividerLocation(150);

        panel_botones.setBackground(new java.awt.Color(255, 255, 153));
        panel_botones.setPreferredSize(new java.awt.Dimension(150, 610));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Grupo 7 - Todos los derechos reservados ©</html>");

        botonListaVendedores.setBackground(new java.awt.Color(255, 102, 153));
        botonListaVendedores.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonListaVendedores.setText("Vendedores");
        botonListaVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaVendedoresActionPerformed(evt);
            }
        });

        botonListaClientes.setBackground(new java.awt.Color(255, 102, 153));
        botonListaClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonListaClientes.setText("Clientes");
        botonListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaClientesActionPerformed(evt);
            }
        });

        botonListaItemsMenu.setBackground(new java.awt.Color(255, 102, 153));
        botonListaItemsMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonListaItemsMenu.setText("Items Menu");
        botonListaItemsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaItemsMenuActionPerformed(evt);
            }
        });

        botonListaPedidos.setBackground(new java.awt.Color(255, 102, 153));
        botonListaPedidos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonListaPedidos.setText("Pedidos");
        botonListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaPedidosActionPerformed(evt);
            }
        });

        label_buscar1.setBackground(new java.awt.Color(255, 102, 102));
        label_buscar1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label_buscar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_buscar1.setText("<html>GESTIÓN<br>DELIVERY</html>");
        label_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 5));
        label_buscar1.setOpaque(true);

        javax.swing.GroupLayout panel_botonesLayout = new javax.swing.GroupLayout(panel_botones);
        panel_botones.setLayout(panel_botonesLayout);
        panel_botonesLayout.setHorizontalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_buscar1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_botonesLayout.createSequentialGroup()
                        .addGroup(panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonListaVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonListaItemsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonListaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        panel_botonesLayout.setVerticalGroup(
            panel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botonesLayout.createSequentialGroup()
                .addComponent(label_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListaVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListaItemsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonListaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_botonesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonListaClientes, botonListaItemsMenu, botonListaPedidos, botonListaVendedores});

        jSplitPane1.setLeftComponent(panel_botones);

        panel_informacion.setBackground(new java.awt.Color(153, 255, 153));
        panel_informacion.setPreferredSize(new java.awt.Dimension(810, 610));
        panel_informacion.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(panel_informacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Configuración en el constructor o inicialización de tu clase `Split`
    
    private void botonListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaPedidosActionPerformed
       cambiarPanel(panelPedido, botonListaPedidos);
    }//GEN-LAST:event_botonListaPedidosActionPerformed

    private void botonListaVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaVendedoresActionPerformed
       cambiarPanel(panelVendedor, botonListaVendedores);
    }//GEN-LAST:event_botonListaVendedoresActionPerformed

    private void botonListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaClientesActionPerformed
       cambiarPanel(panelCliente, botonListaClientes);
    }//GEN-LAST:event_botonListaClientesActionPerformed

    private void botonListaItemsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaItemsMenuActionPerformed
       // AGREGAR ACCION DESACTIVAR BOTON DE LA INTERFAZ QUE SE ESTE MOSTRANDO
        
        cambiarPanel(panelItemMenu, botonListaItemsMenu);
    }//GEN-LAST:event_botonListaItemsMenuActionPerformed

    private void mostrarModal(JDialog modal) {
        modal.setSize(520, 350);
        modal.setLocationRelativeTo(this);
        modal.setVisible(true);
    }
    
    private void mostrarModalEliminar(JDialog modal) {
        modal.setSize(300, 150);
        modal.setLocationRelativeTo(this);
        modal.setVisible(true);
    }
    
     public void cambiarPanel(PanelInformacion panel, JButton boton){
        boton_menu_seleccionado.setEnabled(true);
        boton_menu_seleccionado.setBackground(new Color(255, 102, 153));
        boton_menu_seleccionado.setForeground(Color.BLACK);
        
        boton.setEnabled(false);
        boton.setBackground(Color.BLACK);
        boton.setForeground(Color.WHITE);
        boton_menu_seleccionado = boton;
        
        
        panel_informacion.removeAll();
        panel_informacion.add((JPanel)panel, BorderLayout.CENTER);
        panel_informacion.revalidate();
        panel_informacion.repaint();
        panel.abrirPanel();
    }
     
    /*private void cerrarModales(){
        modal_eliminar.dispose();
        modal_vendedor.dispose();
        modal_cliente.dispose();
        modal_item_menu.dispose();
        modal_pedido.dispose();
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGeneral().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListaClientes;
    private javax.swing.JButton botonListaItemsMenu;
    private javax.swing.JButton botonListaPedidos;
    private javax.swing.JButton botonListaVendedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel label_buscar1;
    private javax.swing.JPanel panel_botones;
    private javax.swing.JPanel panel_informacion;
    // End of variables declaration//GEN-END:variables



}
